In [1]:
import numpy as np
from datetime import date, timedelta

# Create a 3x3x3 array with random values

In [13]:
arr = np.random.rand(3,3,3)
arr

array([[[0.4201633 , 0.72637664, 0.85021625],
        [0.4192626 , 0.09091935, 0.32001397],
        [0.07677136, 0.54492282, 0.97888521]],

       [[0.1690293 , 0.34704217, 0.32943285],
        [0.43874791, 0.27474089, 0.76170219],
        [0.10789954, 0.05883558, 0.21961479]],

       [[0.25550097, 0.28236048, 0.99329889],
        [0.71800778, 0.69379883, 0.66231523],
        [0.20727061, 0.19855389, 0.02685659]]])


# Create a 5x5 matrix with values 1,2,3,4 just below the diagona

In [27]:
arr =  np.diag(np.arange(4) + 1, k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# Create a 8x8 matrix and fill it with a checkerboard pattern

In [31]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# Normalize a 5x5 random matrix

In [32]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
arr

array([[ 1.24918094, -0.73710117, -0.48893001,  0.71682259, -0.49564788],
       [ 0.71030463, -0.00462711,  1.37300306, -1.88055359,  0.59275597],
       [ 0.24425867, -1.57649004, -0.02184476,  0.50993607, -0.83997514],
       [ 0.65125249, -1.68960223,  0.61108046, -1.22148834,  1.18842454],
       [-1.27828109,  1.66097161,  0.96161549,  0.20436466, -0.43942983]])

# How to find common values between two arrays

In [33]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

np.intersect1d(arr1, arr2)


array([2, 3, 6, 7])

#  How to get the dates of yesterday, today and tomorrow

In [34]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2020-08-14 2020-08-15 2020-08-16


# Consider two random array A and B, check if they are equal

In [35]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')

Array1:
[[0.75641628 0.52644756 0.6451681 ]
 [0.56174306 0.35652753 0.22734162]
 [0.47010366 0.90126267 0.63272249]]


Array2:
[[0.19874517 0.33643272 0.78554223]
 [0.16091619 0.34233352 0.71881113]
 [0.72714537 0.28328699 0.5757167 ]]


Equality: False


# Create random vector of size 10 and replace the maximum value by 0

In [44]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.74633544, 0.70501684, 0.10302196, 0.40624257, 0.75588283,
       0.2665456 , 0.        , 0.35141395, 0.83754866, 0.5737664 ])

# How to print all the values of an array?

In [43]:

arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# Subtract the mean of each row of a matrix

In [41]:
arr = np.random.rand(3,3)
arr_mean = arr - arr.mean(axis=1, keepdims=True)

arr_mean


array([[-0.29322672,  0.1678083 ,  0.12541842],
       [-0.19156379, -0.20501964,  0.39658344],
       [ 0.20726518, -0.35330104,  0.14603585]])

# Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [40]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([2., 3., 4., 3., 3.])

# How to get the diagonal of a dot product

In [39]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([25, 41, 49])

# How to find the most frequent value in an array?

In [38]:

arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)


[1 3 9 0 6 2 8 5 7 0 7 7 9 5 2 8 5 8 7 3]


7

# How to get the n largest values of an array?


In [37]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

2

# How to create a record array from a regular array?

In [36]:
arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])